### ISSUE TITLE
Ajouter cert manager a la base

### ISSUE THREAD

**Issue by Simon-Boyer** [ClubCedille/Plateforme-Cedille#234]

**Comment by Simon-Boyer** [comment]
https://github.com/ClubCedille/Plateforme-Cedille/tree/master/system/cert-manager

**Comment by Simon-Boyer** [comment]
https://cert-manager.io/

**Comment by JulienGiguere** [comment]
kubectl config pour lanets-staging: [https://cedille.omni.siderolabs.io/cluster/lanets-staging/overview](omni cidero link)

used this procedure: [https://cert-manager.io/docs/installation/helm/](cert-manager install procedure link)

used previous configs [https://github.com/ClubCedille/Plateforme-Cedille/tree/master/system/cert-manager](github link)

```
  kubectl apply -f issuer-prod.yaml
  kubectl apply -f issuer-staging.yaml
```

What was done: Installed cert-manager that uses letsencrypt on lanets-staging.

Awaiting test to see if it works with [https://github.com/ClubCedille/Plateforme-Cedille/issues/235](contour).

**Comment by JulienGiguere** [comment]
Modifier le champ 'solvers' des fichiers issuer-staging.yaml & issuer-prod.yaml pour utiliser dns au lieu de http .

```
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-token
            key: token
```
